thresh: 14
clusters: [2, 6]
eps: [0.1, 0.15, 0.2]
min_samples: [3, 5, 10]

db_1: {'path': 'data/processed/activity.csv',
        'loc_feats': ['census_tract'],
        'time_feat': 'agg_day_period',
        'target': 'activity_index_total',
        'agg_path': 'data/processed/activity_agg.csv'}
db_2: {'path': 'data/processed/energy.csv',
        'loc_feats': ['zip_code'],
        'time_feat': 'date',
        'target': 'energy',
        'agg_path': 'data/processed/energy_agg.csv'}

db_3: {'path': 'data/processed/CuebiqMicro_Harvey.csv'}

db_4: {'path': 'data/processed/Ida_homecbg_poi.csv',
        'loc_feats': ['home_block_group_id', 'place_id'],
        'time_feat': 'date',
        'target': 'count',
        'agg_path': 'data/processed/Ida_homecbg_poi_agg.csv'}

db_5: {'path': 'data/processed/Ida_CBG_CBG.csv',
        'loc_feats': ['begin_CBG', 'end_CBG'],
        'time_feat': 'date',
        'target': 'count'}

db_6: {'path': 'data/processed/Ida_POI_POI.csv',
        'loc_feats': ['begin_POI', 'end_POI'],
        'time_feat': 'date',
        'target': 'count'}